SELECT TOP (1000) [StudentID]
      ,[FirstName]
      ,[LastName]
      ,[City]
      ,[Age]
      ,[Grade]
      ,[Score]
      ,[Subject]
      ,[EnrollmentDate]
      ,[FeesPaid]
  FROM [BASICS].[dbo].[Students]
